# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoreRN

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'CxxBridge', # Include if RN >= 0.47
    'RCTNetwork',

  ]
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'yoga', path: "../node_modules/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'

end
